baseURL = "https://html0727.github.io/"
languageCode = "zh-cn"
title = "HTML0727's Blog"
theme = "m10c"

[params]
  author = "HTML0727"
  description = "来自 GitHub 的 README 介绍"
  avatar = "https://github.com/HTML0727.png"

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/HTML0727"

  [[params.social]]
    name = "X"
    url = "https://x.com/Makki_Yaku947"
