baseURL = "https://html0727.github.io/"
defaultContentLanguage = "zh"
title = "HTML0727's Blog"
theme = "m10c"

[languages]

  [languages.zh]
    languageName = "中文"
    weight = 1
    contentDir = "content/zh"
    [languages.zh.params]
      author = "HTML0727"
      description = "来自 GitHub 的 README 介绍"
      avatar = "https://github.com/HTML0727.png"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      author = "HTML0727"
      description = "Personal blog powered by Hugo"
      avatar = "https://github.com/HTML0727.png"

  [languages.ja]
    languageName = "日本語"
    weight = 3
    contentDir = "content/ja"
    [languages.ja.params]
      author = "HTML0727"
      description = "GitHub README からの自己紹介"
      avatar = "https://github.com/HTML0727.png"
